config/routes.rb
Rails.application.routes.draw do
  root to: "comments#index"

  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to comments_path
    else
      rander :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to comments_path
    else
      rander :edit
    end  
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

      redirect_to comments_path
  end


  private 

  def comment_params
  	params.require(:comment).permit(:name, :text, :date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<h2 >Редактирование коментария</h2>

<%= form_with(model: @comment, local: true) do |form| %>
<div>
  <p><%= form.label :name, "Email" %></p>
  <p><%= form.text_field :name %></p>

  <p><%= form.label :text, "Текст" %></p>
  <p><%= form.text_area :text, rows: 5 %></p>
  	
  <p><%= form.label :date, "Дата создания" %></p>
  <p><%= form.text_field :date %></p>
  
  <p><%= form.submit "Сохранить изменения" %></p>

</div>  
<% end %>

app/views/comments/index.html.erb
<h2>Все комментарии.</h2>

<% @comments.each do |comment| %>

	<div class = "comment">	
		<p>Email: <%= comment.name %></p>
		<p>Текст:<strong><%=  comment.text %></strong></p>
		<p>Дата создания: <%= comment.date %></p>
		<hr>	
	</div>

    | <%= link_to "Изменить", edit_comment_path(comment) %> |
     <%= button_to "Удалит", comment_path(comment), formmethod: :delete, data: { confirm: 'Вы уверены?' } %>
  <hr>
<% end %>


<%= form_with model: @comment, local: true do |form| %>
<div>
  <p><%= form.label :name, "Email" %></p>
  <p><%= form.text_field :name %></p>

  <p><%= form.label :text, "Текст" %></p>
  <p><%= form.text_area :text, rows: 5 %></p>
  	
  <p><%= form.label :date, "Дата создания" %></p>
  <p><%= form.text_field :date %></p>
  
  <p><%= form.submit 'Добавить комментарий' %></p>

</div>  
<% end %>

app/views/comments/new.html.erb
<h2 >Новый коментарий</h2>

<%= form_with model: @comment, local: true  do |form| %>
<div>
  <p><%= form.label :name, "Email" %></p>
  <p><%= form.text_field :name %></p>

  <p><%= form.label :text, "Текст" %></p>
  <p><%= form.text_area :text, rows: 5 %></p>
  	
  <p><%= form.label :date, "Дата создания" %></p>
  <p><%= form.text_field :date %></p>
  
  <p><%= form.submit 'Добавить комментарий' %></p>

</div>  
<% end %>

app/views/comments/show.html.erb
<h3><%= @comment.name %></h3>
	<p><%= @comment.text %></p><br>

	<nav>
     <%= link_to "Изменить", edit_comment_path(@comment) %> |
     <%= link_to "Все комментарии.", comments_path(@comments) %>
  </nav>
  <br>

<%= button_to "Удалить", comment_path(@comment), formmethod: :delete, data: {confirm: "Удалить?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommentsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>